[theme]
base="dark"
primaryColor = "#F63366"
backgroundColor = "linear-gradient(to right, #1c0522eb 51%,transparent 100%)"
secondaryBackgroundColor = "#752237"
textColor = "#ffffff"
font = "sans serif"
